# Be sure to restart your server when you modify this file.

# Version of your assets, change this if you want to expire all your assets.
Rails.application.config.assets.version = '1.0'

# Add additional assets to the asset load path
# Rails.application.config.assets.paths << Emoji.images_path

# Precompile additional assets.
# application.js, application.css, and all non-JS/CSS in app/assets folder are already added.
# Rails.application.config.assets.precompile += %w( search.js )

Rails.application.config.assets.precompile += %w( all.css )
Rails.application.config.assets.precompile += %w( animate.css )
Rails.application.config.assets.precompile += %w( awesome-bootstrap-checkbox.css )
Rails.application.config.assets.precompile += %w( blueimp-gallery.min.css )
Rails.application.config.assets.precompile += %w( bootstrap-clockpicker.min.css )
Rails.application.config.assets.precompile += %w( bootstrap-datepicker3.min.css )
Rails.application.config.assets.precompile += %w( bootstrap-datetimepicker.min.css )
Rails.application.config.assets.precompile += %w( bootstrap-editable.css )
Rails.application.config.assets.precompile += %w( bootstrap-tour.min.css )
Rails.application.config.assets.precompile += %w( bootstrap.css )
Rails.application.config.assets.precompile += %w( bootstrap.min.css )
Rails.application.config.assets.precompile += %w( c3.min.css )
Rails.application.config.assets.precompile += %w( chartist.css )
Rails.application.config.assets.precompile += %w( codemirror.css )
Rails.application.config.assets.precompile += %w( dataTables.bootstrap.min.css )
Rails.application.config.assets.precompile += %w( footable.core.min.css )
Rails.application.config.assets.precompile += %w( fullcalendar.min.css )
Rails.application.config.assets.precompile += %w( fullcalendar.print.css )
Rails.application.config.assets.precompile += %w( jquery.bootstrap-touchspin.min.css )
Rails.application.config.assets.precompile += %w( ladda-themeless.min.css )
Rails.application.config.assets.precompile += %w( metisMenu.css )
Rails.application.config.assets.precompile += %w( select2-bootstrap.css )
Rails.application.config.assets.precompile += %w( select2.css )
Rails.application.config.assets.precompile += %w( start-rating.css )
Rails.application.config.assets.precompile += %w( static_custom.css )
Rails.application.config.assets.precompile += %w( style.css )
Rails.application.config.assets.precompile += %w( summernote-bs3.css )
Rails.application.config.assets.precompile += %w( summernote.css )
Rails.application.config.assets.precompile += %w( sweet-alert.css )
Rails.application.config.assets.precompile += %w( toastr.min.css )


Rails.application.config.assets.precompile += %w( jquery.flot.spline/index.js )
Rails.application.config.assets.precompile += %w( bootstrap-clockpicker.min.js )
Rails.application.config.assets.precompile += %w( bootstrap-datepicker.min.js )
Rails.application.config.assets.precompile += %w( bootstrap-datetimepicker.min.js )
Rails.application.config.assets.precompile += %w( bootstrap-editable.min.js )
Rails.application.config.assets.precompile += %w( bootstrap-tour.min.js )
Rails.application.config.assets.precompile += %w( bootstrap.min.js )
Rails.application.config.assets.precompile += %w( buttons.bootstrap.min.js )
Rails.application.config.assets.precompile += %w( buttons.html5.min.js )
Rails.application.config.assets.precompile += %w( buttons.print.min.js )
Rails.application.config.assets.precompile += %w( c3.min.js )
Rails.application.config.assets.precompile += %w( Chart.min.js )
Rails.application.config.assets.precompile += %w( chartist.min.js )
Rails.application.config.assets.precompile += %w( charts.js )
Rails.application.config.assets.precompile += %w( codemirror.js )
Rails.application.config.assets.precompile += %w( curvedLines.js )
Rails.application.config.assets.precompile += %w( d3.min.js )
Rails.application.config.assets.precompile += %w( dataTables.buttons.min.js )
Rails.application.config.assets.precompile += %w( footable.all.min.js )
Rails.application.config.assets.precompile += %w( fullcalendar.min.js )
Rails.application.config.assets.precompile += %w( homer.js )
Rails.application.config.assets.precompile += %w( icheck.min.js )
Rails.application.config.assets.precompile += %w( index.js )
Rails.application.config.assets.precompile += %w( javascript.js )
Rails.application.config.assets.precompile += %w( jquery-ui.min.js )
Rails.application.config.assets.precompile += %w( jquery.blueimp-gallery.min.js )
Rails.application.config.assets.precompile += %w( jquery.bootstrap-touchspin.min.js )
Rails.application.config.assets.precompile += %w( jquery.flot.js )
Rails.application.config.assets.precompile += %w( jquery.flot.pie.js )
Rails.application.config.assets.precompile += %w( jquery.flot.resize.js )
Rails.application.config.assets.precompile += %w( jquery.min.js )
Rails.application.config.assets.precompile += %w( jquery.nestable.js )
Rails.application.config.assets.precompile += %w( jquery.peity.min.js )
Rails.application.config.assets.precompile += %w( jquery.slimscroll.min.js )
Rails.application.config.assets.precompile += %w( jquery.validate.min.js )
Rails.application.config.assets.precompile += %w( ladda.jaquery.min.js )
Rails.application.config.assets.precompile += %w( ladda.min.js )
Rails.application.config.assets.precompile += %w( metisMenu.min.js )
Rails.application.config.assets.precompile += %w( moment.js )
Rails.application.config.assets.precompile += %w( moment.min.js )
Rails.application.config.assets.precompile += %w( select2.min.js )
Rails.application.config.assets.precompile += %w( spin.min.js )
Rails.application.config.assets.precompile += %w( start-rating.min.js )
Rails.application.config.assets.precompile += %w( summernote.min.js )
Rails.application.config.assets.precompile += %w( sweet-alert.min.js )
Rails.application.config.assets.precompile += %w( toastr.min.js )
